# Generated by Django 4.2.1 on 2024-02-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_choice_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='slug',
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='question'),
            preserve_default=False,
        ),
    ]
